#!/bin/bash

COLOR=$1
ICON_PACK=~/.local/share/icons/copycat

FLAVOR="$ICON_PACK/reserved/folder-flavors/$COLOR"
PLACES="$ICON_PACK/places/scalable"

if [ ! -e $FLAVOR ]; then
    echo Flavor does not exists
fi

TARGETS=(
    application-x-gnome-saved-search
    bookmark-missing
    certificate-server
    desktop
    favorites
    folder
    folder_2
    folder_home
    folder_home2
    folder_html
    folder_man
    #folder_open
    #folder_pictures
    folder_wordprocessing
    folder-3dprint
    folder-activities
    folder-add
    folder-android
    folder-applications
    folder-arduino
    folder-backup
    folder-bookmark
    folder-bookmarks
    folder-books
    folder-cd
    folder-CloudStation
    folder-copy-cloud
    folder-decrypted
    folder-development
    folder-documents
    folder-download
    folder-download-open
    folder-downloads
    #folder-drag-accept
    folder-dropbox
    folder-ecrypted
    folder-encrypted
    folder-favorites
    folder-games
    folder-gdrive
    folder-git
    folder-github
    folder-gitlab
    folder-gnome
    #folder-go
    folder-google-drive
    folder-home
    folder-home2
    folder-html
    folder-image
    folder-image-people
    folder-images
    folder-important
    folder-java
    folder-kde
    folder-linux
    folder-locked
    folder-mail
    folder-mail-cloud
    folder-mega
    folder-megasync
    folder-meocloud
    folder-music
    #folder-music-open
    folder-network
    #folder-nextcloud
    folder-onedrive
    #folder-open
    folder-owncloud
    folder-pcloud
    #folder-picture
    #folder-pictures
    #folder-pictures-open
    folder-print
    folder-private
    #folder-projects
    folder-public
    folder-publicshare
    #folder-publicshare-open
    folder-recent
    folder-remote
    folder-remote-apf
    folder-remote-ftp
    folder-remote-nfs
    folder-remote-smb
    folder-remote-ssh
    folder-root
    folder-saved-search
    folder-script
    folder-snap
    folder-sounde
    folder-steam
    folder-sync
    folder-syncthing
    folder-synology
    folder-system
    #folder-tar
    folder-temp
    folder-templates
    folder-templates-open
    folder-text
    folder-torrent
    folder-txt
    folder-unlocked
    folder-vbox
    #folder-video
    #folder-video-alt
    #folder-videos
    #folder-visiting
    folder-wine
    folder-yandex-disk
    gnome-ccdesktop
    gnome-desktop
    gnome-desktop-config
    gnome-folder
    #gnome-gnomes-fs-blockdev
    gnome-fs-bookmark
    gnome-fs-bookmark-missing
    gnome-fs-desktop
    gnome-fs-directory
    gnome-fs-directory-accept
    #gnome-fs-directory-open
    #gnome-fs-directory-visiting
    #gnome-fs-ftp
    gnome-fs-home
    gnome-fs-network
    gnome-fs-nfs
    gnome-fs-share
    gnome-fs-smb
    gnome-home
    #gnome-mime-x-directory-share
    #gnome-mime-x-smb-share
    #gnome-mime-x-directory-smb-workgroup
    #gnome-network
    gtk-directory
    #gtk-network
    inode-directory
    insync-folder
    knetattach
    library-music
    #neat
    network
    network_local
    network-manager
    network-server
    #network-server-database
    network-workgroup
    #redhat-system-group
    repository
    stock_bookmark
    stock_delete_bookmark
    stock_folder
    
    stock_open
    stock_shared-by-me
    stock_shared-to-me
    
    user-bookmarks
    user-desktop
    user-home
    user-home-home-drag-accept
    user-home-open
    user-images
    user-pictures
    user-share
)  
for icon in $FLAVOR/*.svg; do
    ln -s
    done